name: trabajo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/graduado.png
    - assets/profesor.png
    - assets/home.jpg
    - assets/idea.png
    - assets/marco.png
    - assets/meto.png
    - assets/plantear.png
    - assets/reco.png
    - assets/revision.png
    - assets/quizas.png
    - assets/prioridad.png
    - assets/limites.png
    - assets/investigacion.png
    - assets/diana.png
    - assets/diagnostico.png
    - assets/bombilla.png
    - assets/t.png
    - assets/gt.png
    - assets/bing.png
    - assets/gg.png
    - assets/what.webp
    - assets/problema.png
    - assets/palabra.png
    - assets/pdf.png
    - assets/lista.png
    - assets/gmail.png
    - assets/conclu.png
    - assets/pasos/paso3/img1.png
    - assets/pasos/paso4/img1.png
    - assets/pasos/paso4/img2.png
    - assets/pasos/paso4/img3.png
    - assets/pasos/paso4/img4.png
    - assets/pasos/paso5/img1.png
    - assets/pasos/paso5/img2.png
    - assets/pasos/paso5/img3.png
    - assets/pasos/paso5/img4.png
    - assets/pasos/paso5/img5.png
    - assets/pasos/pasos6/img1.png
    - assets/pasos/pasos6/img2.png
    - assets/pasos/pasos6/img3.png
    - assets/pasos/pasos6/img4.png
    - assets/pasos/pasos6/img5.png
    - assets/pasos/paso7/img1.png
    - assets/pasos/paso7/img2.png
    - assets/advertencia.png
    - assets/logo.png