name: trabajo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/graduado.png
    - assets/profesor.png
    - assets/home.jpg
    - assets/idea.png
    - assets/marco.png
    - assets/meto.png
    - assets/plantear.png
    - assets/reco.png
    - assets/revision.png
    - assets/quizas.png
    - assets/prioridad.png
    - assets/limites.png
    - assets/investigacion.png
    - assets/diana.png
    - assets/diagnostico.png
    - assets/bombilla.png
    - assets/t.png
    - assets/problema.png